In [66]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

In [67]:
ANN = Sequential()

In [68]:
ANN.add(Dense(2,activation="sigmoid",input_dim=3))
ANN.add(Dense(3,activation="sigmoid"))
ANN.add(Dense(2))

In [69]:
ANN.layers[0].get_weights()

[array([[-0.49046737, -0.5760417 ],
        [-0.9606068 ,  0.4081005 ],
        [ 0.6869947 , -0.1004681 ]], dtype=float32),
 array([0., 0.], dtype=float32)]

In [70]:
w12=np.array([[0.2,-0.3],[0.4,0.1],[-0.5,0.2]])
bias1=np.array([0.4,0.2])
weights1=[w12,bias1]
weights1

ANN.layers[0].set_weights(weights1)

In [71]:
ANN.layers[1].get_weights()

[array([[ 0.17228007, -0.6467335 , -0.39491773],
        [ 0.51604843, -0.8810123 ,  0.4276421 ]], dtype=float32),
 array([0., 0., 0.], dtype=float32)]

In [72]:
w23=np.array([[-0.3,0.2,0.6],[-0.2,-0.1,-0.2]])
bias2=np.array([0.1,0.1,0.2])
weights2=[w23,bias2]
weights2

ANN.layers[1].set_weights(weights2)

In [73]:
ANN.layers[2].get_weights()

[array([[ 0.7612479 , -0.9758356 ],
        [ 0.29365706, -1.0115296 ],
        [-0.20340216, -0.5891801 ]], dtype=float32),
 array([0., 0.], dtype=float32)]

In [74]:
w34=np.array([[0.3,0.2],[-0.5,0.5],[-0.7,0.2]])
bias3=np.array([0.1,0.2])
weights3=[w34,bias3]
weights3

ANN.layers[2].set_weights(weights3)

In [75]:
from keras import optimizers
sgd = optimizers.SGD(lr=0.9)
ANN.compile(loss='mean_squared_error', optimizer=sgd,metrics=['accuracy'])

In [82]:
x=np.array([[1,0,1]])
y=np.array([[1,0]])
ANN.fit(x,y,epochs=1)

Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.0000e+00 - acc: 1.0000


In [83]:
for i in range(3):
  print(ANN.layers[i].get_weights())
  print("\n\n\n\n\n")

[array([[ 0.14698297, -0.2676921 ],
       [ 0.4       ,  0.1       ],
       [-0.5530171 ,  0.23230793]], dtype=float32), array([0.34698293, 0.23230793], dtype=float32)]






[array([[-0.35377687,  0.04268263,  0.4303021 ],
       [-0.26353902, -0.26081303, -0.37395692]], dtype=float32), array([-0.01741019, -0.20420223, -0.12883817], dtype=float32)]






[array([[ 0.6019747 ,  0.06569678],
       [-0.0424867 ,  0.29345083],
       [-0.19150932, -0.02946927]], dtype=float32), array([ 0.85634714, -0.13657345], dtype=float32)]








In [84]:
weightupdate1=[x1 - x2 for (x1, x2) in zip(weights1, model.layers[0].get_weights())]

In [85]:
weightupdate1

[array([[ 5.27389169e-02, -3.09468985e-02],
        [-5.96046446e-09, -1.49011611e-09],
        [ 5.27389646e-02, -3.09469134e-02]]),
 array([ 0.05273896, -0.03094691])]

In [86]:
weightupdate2=[x1 - x2 for (x1, x2) in zip(weights2, model.layers[1].get_weights())]
weightupdate2

[array([[0.05091972, 0.15451205, 0.16645855],
        [0.06031101, 0.15762868, 0.17027991]]),
 array([0.11150369, 0.29839817, 0.32213651])]

In [87]:
weightupdate3=[x1 - x2 for (x1, x2) in zip(weights3, model.layers[2].get_weights())]
weightupdate3

[array([[-0.30187656,  0.13453055],
        [-0.45741196,  0.20678163],
        [-0.50838652,  0.22973308]]), array([-0.7557325 ,  0.33698137])]